version: "3.9"

services:

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: stsdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: stspassw
      MYSQL_USER: stsuser
    networks:
      - sts_network
    volumes:
      - ../var/mariadb/:/var/lib/mysql
      - ../var/log/mariadb:/var/log/mysql
    ports:
      - "8889:3306"

  php:
    container_name: php
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - sts_network

networks:
  sts_network:
    driver: bridge
    name: sts_network
